# SDD sidecar pointer — generated by install-spec-sidecar.sh
Canonical source: spec/template-context/core-instructions/AGENT_OPERATING_SYSTEM.md
Use spec/ as the SDD sidecar and keep runnable code in project root.
This is the recommended default workspace inside a real project.
Do not clone or copy the full framework repository into this project unless the user explicitly asks for a standalone workspace.
No code before approved spec and consistent plan.
