// Spec 031 — the AI request queue. The builder publishes requests here; the
// user's agent session claims them over MCP and answers with proposals. This
// module deliberately imports NO spec writers: a proposal can never touch
// specs/ — the only write path is the user's acceptance in the builder, which
// goes through the existing section/task/board/bitácora routes.
//
// Storage: one human-readable JSON file per request under
// `<sddRoot>/.sdd/requests/`, so the queue survives server restarts and can
// be inspected with any editor. File names sort chronologically (timestamp
// prefix), which makes FIFO a directory listing.

import { randomUUID } from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { withFileLock } from "./file-lock.js";
import { resolveSddRoot } from "./workspace.js";

export type AiRequestType = "draft-field" | "structure-idea";

export type AiRequestStatus =
  | "pending"
  | "in_progress"
  | "answered"
  | "accepted"
  | "rejected"
  | "cancelled";

export type AiRequestResolution = "accepted" | "rejected" | "cancelled";

export type AiTargetKind = "section" | "task" | "note" | "bitacora";

export interface AiRequestTarget {
  kind: AiTargetKind;
  /** Spec the field belongs to, when it belongs to one. */
  specId?: string;
  /** Field id inside its surface: section key, task line, note id, bitacora kind+file. */
  ref: string;
}

export interface AiRequest {
  id: string;
  type: AiRequestType;
  target?: AiRequestTarget;
  /** Text of the field at request time, so the agent needs no second lookup. */
  currentText?: string;
  instruction: string;
  status: AiRequestStatus;
  createdAt: string;
  agent?: string;
  startedAt?: string;
  proposal?: string;
  answeredAt?: string;
  resolvedAt?: string;
}

export interface CreateAiRequestInput {
  type: AiRequestType;
  target?: AiRequestTarget;
  currentText?: string;
  instruction: string;
}

export interface AgentPresence {
  agent: string;
  lastSeenAt: string;
}

/** The full lifecycle; anything not listed here is an illegal transition. */
const TRANSITIONS: Record<AiRequestStatus, AiRequestStatus[]> = {
  pending: ["in_progress", "cancelled"],
  in_progress: ["answered", "cancelled"],
  answered: ["accepted", "rejected"],
  accepted: [],
  rejected: [],
  cancelled: []
};

const PRESENCE_FILE = "agent-presence.json";

/**
 * Monotonic id prefix. `Date.now()` alone is not enough: two requests created
 * inside the same millisecond got the same prefix, so the FIFO order that
 * `nextAiRequest` promises fell through to comparing random uuid suffixes —
 * whichever sorted first won. Caught by a flaky ordering test. The builder's
 * server is the only writer, so a process-local monotonic counter is the whole
 * fix. Padded so lexicographic filename order stays numeric order.
 */
let lastStamp = 0;
function nextStamp(): string {
  const now = Date.now();
  lastStamp = now > lastStamp ? now : lastStamp + 1;
  return String(lastStamp).padStart(14, "0");
}

async function requestsDir(projectRoot: string): Promise<string> {
  return path.join(await resolveSddRoot(projectRoot), ".sdd", "requests");
}

function requestPath(dir: string, id: string): string {
  // Ids are generated by this module (timestamp + uuid slice); reject anything
  // else so an id can never step outside the requests folder.
  if (!/^[0-9]+-[0-9a-f-]+$/.test(id)) {
    throw new Error(`Invalid AI request id: ${JSON.stringify(id)}`);
  }
  return path.join(dir, `${id}.json`);
}

async function writeRequest(dir: string, request: AiRequest): Promise<void> {
  await fs.writeFile(requestPath(dir, request.id), `${JSON.stringify(request, null, 2)}\n`, "utf8");
}

async function readRequest(dir: string, id: string): Promise<AiRequest> {
  let raw: string;
  try {
    raw = await fs.readFile(requestPath(dir, id), "utf8");
  } catch {
    throw new Error(`AI request not found: ${id}`);
  }
  return JSON.parse(raw) as AiRequest;
}

function assertTransition(request: AiRequest, to: AiRequestStatus): void {
  if (!TRANSITIONS[request.status]?.includes(to)) {
    throw new Error(
      `Illegal AI request transition for ${request.id}: ${request.status} -> ${to}. ` +
        `Allowed from ${request.status}: ${TRANSITIONS[request.status]?.join(", ") || "(none, terminal)"}.`
    );
  }
}

export async function createAiRequest(projectRoot: string, input: CreateAiRequestInput): Promise<AiRequest> {
  if (!input.instruction?.trim()) {
    throw new Error("AI request needs a non-empty instruction.");
  }
  if (input.type === "draft-field" && !input.target) {
    throw new Error("A draft-field request needs a target ({ kind, specId?, ref }).");
  }
  const dir = await requestsDir(projectRoot);
  await fs.mkdir(dir, { recursive: true });
  const request: AiRequest = {
    id: `${nextStamp()}-${randomUUID().slice(0, 8)}`,
    type: input.type,
    ...(input.target ? { target: input.target } : {}),
    ...(input.currentText !== undefined ? { currentText: input.currentText } : {}),
    instruction: input.instruction.trim(),
    status: "pending",
    createdAt: new Date().toISOString()
  };
  await writeRequest(dir, request);
  return request;
}

/** Every request, oldest first. A workspace without a queue lists as empty. */
export async function listAiRequests(projectRoot: string): Promise<AiRequest[]> {
  const dir = await requestsDir(projectRoot);
  let names: string[];
  try {
    names = (await fs.readdir(dir)).filter((n) => n.endsWith(".json") && n !== PRESENCE_FILE);
  } catch {
    return [];
  }
  const requests = await Promise.all(names.sort().map((n) => readRequest(dir, n.replace(/\.json$/, ""))));
  return requests;
}

export async function getAgentPresence(projectRoot: string): Promise<AgentPresence | null> {
  try {
    const raw = await fs.readFile(path.join(await requestsDir(projectRoot), PRESENCE_FILE), "utf8");
    return JSON.parse(raw) as AgentPresence;
  } catch {
    return null;
  }
}

async function touchAgentPresence(dir: string, agent: string): Promise<void> {
  await fs.mkdir(dir, { recursive: true });
  const presence: AgentPresence = { agent, lastSeenAt: new Date().toISOString() };
  await fs.writeFile(path.join(dir, PRESENCE_FILE), `${JSON.stringify(presence, null, 2)}\n`, "utf8");
}

/**
 * Claim the oldest pending request for `agent`: pending -> in_progress.
 * An empty queue returns null explicitly (R2) — the poll itself still records
 * presence, which is what "agente conectado" means in the builder (R6).
 */
export async function nextAiRequest(projectRoot: string, agent: string): Promise<AiRequest | null> {
  const dir = await requestsDir(projectRoot);
  // The lock serializes concurrent claims in-process so two polls can never
  // walk away with the same request.
  return withFileLock(dir, async () => {
    await touchAgentPresence(dir, agent);
    const pending = (await listAiRequests(projectRoot)).find((r) => r.status === "pending");
    if (!pending) return null;
    assertTransition(pending, "in_progress");
    const claimed: AiRequest = {
      ...pending,
      status: "in_progress",
      agent,
      startedAt: new Date().toISOString()
    };
    await writeRequest(dir, claimed);
    return claimed;
  });
}

/** Attach the agent's proposal: in_progress -> answered. Never writes specs/. */
export async function respondAiRequest(projectRoot: string, id: string, proposal: string): Promise<AiRequest> {
  if (!proposal?.trim()) {
    throw new Error("AI request response needs a non-empty proposal.");
  }
  const dir = await requestsDir(projectRoot);
  return withFileLock(dir, async () => {
    const request = await readRequest(dir, id);
    assertTransition(request, "answered");
    const answered: AiRequest = {
      ...request,
      status: "answered",
      proposal,
      answeredAt: new Date().toISOString()
    };
    await writeRequest(dir, answered);
    return answered;
  });
}

/**
 * Close a request: accepted/rejected from answered, cancelled from pending or
 * in_progress (R8 — a stuck request is the user's to kill).
 */
export async function resolveAiRequest(
  projectRoot: string,
  id: string,
  resolution: AiRequestResolution
): Promise<AiRequest> {
  const dir = await requestsDir(projectRoot);
  return withFileLock(dir, async () => {
    const request = await readRequest(dir, id);
    assertTransition(request, resolution);
    const resolved: AiRequest = { ...request, status: resolution, resolvedAt: new Date().toISOString() };
    await writeRequest(dir, resolved);
    return resolved;
  });
}
